[phases.setup]
nixPkgs = ["chromium", "nss", "mesa", "libdrm", "expat", "libxcb", "libxkbcommon", "at-spi2-atk", "cups", "dbus", "libgbm"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "playwright install chromium --with-deps"
]
